telegram_token: "8306266645:AAHL67De1XJr2M6BcGTiJmY85ysJa-D-M3s"
openai_api_key: "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"
openai_api_base: null  # Leave as null unless you're using a custom API base (e.g., proxy)

allowed_telegram_usernames: []  # Leave empty to allow everyone

new_dialog_timeout: 86400  # 24 hours auto reset

return_n_generated_images: 1
n_chat_modes_per_page: 1
image_size: "512x512"
enable_message_streaming: true

# prices (not used in Zara mode, but kept if needed later)
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
