available_text_models: ["gpt-4o"]

info:
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is a special variant of GPT-4 designed for optimal performance and accuracy. Zara uses this model to chat with you in a flirty and intelligent way. 💕

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 4
      cheap: 3
